### ISSUE TITLE
Comboboxes always show first option

### ISSUE THREAD

**Issue by xBsWYA2wYfuxW0FB** [NotToDisturb/Decomp-Trainer-Editor#1]
No matter the chosen option, it always show the first one:

![imagen](https://user-images.githubusercontent.com/19817822/96324988-e0201c80-1024-11eb-97a9-ec798467f01b.png)

**Comment by NotToDisturb** [comment]
Is it all comboboxes or only the picture one? I did make a mistake with the filter I passed and it has been fixed, should be up tomorrow morning.

**Comment by xBsWYA2wYfuxW0FB** [comment]
I believe it's all of them. At least **Trainer class**, **Trainer pic** and **Encounter music**.

**Comment by NotToDisturb** [comment]
Well that's interesting, just found the error: same as pic combobox, wrong filter type. Must have accidentally replaced all of them or something, will be fixed by tomorrow. You can use an earlier version, no additional functionalities have been implemented since 1.0.

**Comment by NotToDisturb** [comment]
Fixed in version 1.1.3
