### ISSUE TITLE
Adding an option to add custom moves

### ISSUE THREAD

**Issue by xBsWYA2wYfuxW0FB** [NotToDisturb/Decomp-Trainer-Editor#2]
As you probably know, trainer teams can have several types as for example "Custom moves without held items" and etc. It could be great to have an option to grant "Default moves" teams the "Custom moves" type.

**Comment by NotToDisturb** [comment]
Another bug from this specific version. You can actually see a "Moves:" label, but after some changes in this version I forgot to add the comboboxes to the panel. Will upload a fix tomorrow.

**Comment by NotToDisturb** [comment]
Fixed in version 1.1.3
